### ISSUE TITLE
Filter out "video" type recordings

### ISSUE THREAD

**Issue by HeresJonny** [marc2k3/foo_musicbrainz#3]
Example: https://musicbrainz.org/release/866c38cb-5a60-4b6f-b3da-df9d0a93ccf3

Tagging such a release in foobar2000 will never work because it contains several videos which are not shown by fb2k's DVD-parser so that the playlist is always missing tracks. Do you see any way to filter out videos so that matching becomes possible?

See also conversation here: https://musicbrainz.org/edit/64044280

Thanks for this great plug-in!

**Comment by marc2k3** [comment]
First of all, what a terrible reason for the edit. You shouldn't be allowed anywhere near the database. 😛 

And there are 2 issues here... 

Artist/album searches only get a track count in the summary, not any details on tracks/recordings. There is simply no way I'm adjusting the logic here to return albums where the track counts don't match.

It could be theoretically possible to filter out videos when performing a search by MBID but I see no compelling reason to do so when foobar2000 can easily tag mp4/mkv videos.

If you don't want to rip the videos, just add 2 dummy files to your selection, tag them and then throw them away when done.

**Comment by HeresJonny** [comment]
There is always a work-around. For example, one could always use Picard instead of your plug-in. Or one could use a completely different music player than foobar2000. Or one could just play the DVD-A in a DVD player. But I didn't ask for a work-around. So you say no for no good reason, which is your right as a developer. You have no right to dish out insults, though.

**Comment by HeresJonny** [comment]
foo_discogs also offers an option to filter out video tracks. Please re-consider.

**Comment by marc2k3** [comment]
> There is always a work-around

Can't remember who said that but it seems apt.
