### ISSUE TITLE
MUSICBRAINZ_RELEASETRACKID & MUSICBRAINZ_TRACKID

### ISSUE THREAD

**Issue by smoralis** [marc2k3/foo_musicbrainz#4]
Could you check this difference between picard and foo_musicbrainz.
It seems that the MBID's are swapped.

![picardvsfoo_musicbrainz](https://user-images.githubusercontent.com/3080179/65628265-c7883300-dfd9-11e9-9309-a4a68b55f75e.png)

Original values are from foo_musicbrainz and new values from picard.

json is at  media[0].tracks[3]
http://musicbrainz.org/ws/2/release/5f91cb35-0c42-4766-9d23-96ddc5891063?fmt=json&inc=artists+labels+recordings+release-groups+artist-credits+isrcs

Thanks.

**Comment by marc2k3** [comment]
What this component has always done is write the names used for FLAC/vorbis comments, even when writing to mp3/m4a. I don't have that album but I tagged 13 flac files with foo_musicbrainz and then opened them in Picard...

![Untitled](https://user-images.githubusercontent.com/34617027/65630733-e08ae700-dfcd-11e9-94a4-dd72ef19d4d6.png)

See how they're magically aligned!!

**Comment by smoralis** [comment]
Resolved.

Fuck the tag mappings, what a mess!!

MusicBrainz Recording Id > internal = musicbrainz_recordingid > mp3 = UFID > Vorbis  = **MUSICBRAINZ_TRACKID**

MusicBrainz Track Id > internal = **musicbrainz_trackid** > mp3 = TXXX:MusicBrainz Release Track Id > Vorbis = MUSICBRAINZ_RELEASETRACKID
