### ISSUE TITLE
Vorbis/Ape tags vs. id3 tags

### ISSUE THREAD

**Issue by HeresJonny** [marc2k3/foo_musicbrainz#5]
This component writes APE/VORBIS tags for any kind of file, even when tagging MP3. As APE tags are possible in MP3 that is ok. But when tags are re-written to id3 they become wrong. Musicbrainz tags in id3 format use spaces, whereas in APE format they use underscores.

I'm not sure at this point where the responsibilty for this should lie but I lean towards the component. When copying/rewriting tags between different formats foobar2000 core is not aware of special requirements for Musicbrainz. The component might intervene here, but this would mean enumerating all required tag names for Musicbrainz tags for both APE and ID3 tags specifically, maybe even in the user dialogue.

See third party software problems here: https://forum.kodi.tv/showthread.php?tid=350629

**Comment by marc2k3** [comment]
Just to be clear, it uses Vorbis comment NAMES. It doesn't write the wrong tags to mp3s!

Anyway, this is something the original component started doing over 10 years ago long before I had any interest but I'm fully behind it and I won't be changing it. If you want compatibility with other software, I suggest using Picard.

I do apologise for the fact this is not documented. It's important and people should know about it before they start using it so again, I'm sorry about that.

**Comment by marc2k3** [comment]
I've just updated the webpage here: https://marc2k3.github.io/foo_musicbrainz.html#tag-mapping

**Comment by HeresJonny** [comment]
The component is doing everything correctly and no need to apologize. The problem occurs only if the foobar2000 internal function of re-tagging MP3 is used and tags are propagated to ID3.

In this stage I was asking for you opinion and offered some suggestions. One solution would be to write MP3 tags directly in the correct format. Another option would be to solve this in foobar2000 core.

**Comment by marc2k3** [comment]
I've since updated the webpage with a few more exceptions related to `id3` tagging. I'm going to close this as I won't be modifying the current behaviour.

**Comment by phw** [comment]
If I understand the issue correctly the component has limited control over this, right? I guess the best solution would be if foobar2000 itself would be aware of proper mapping of the MBID tags. That way the internal tag names in f2k could stay the same for all formats, but could be written to the proper named tags depending on format. Has this ever been discussed with the f2k developers?

**Comment by HeresJonny** [comment]
Feel free to chime in: https://hydrogenaud.io/index.php?topic=70623.msg978971#msg978971

**Comment by marc2k3** [comment]
Sure, go ahead and request this from the fb2k developers. I have zero interest but would update the component to make it compliant with any new changes.

Remember you don't even need to mention what foo_musicbrainz does or does not do. You want comaptibilty with Picard/other apps so leave me/this out of it.
